# Generated by Django 4.0.5 on 2022-07-01 16:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('sinopsis', models.TextField(max_length=400)),
                ('poster', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('createDT', models.CharField(default=datetime.datetime(2022, 7, 1, 16, 7, 15, 707570), max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('data_birth', models.CharField(max_length=32, null=True)),
                ('createDT', models.CharField(default=datetime.datetime(2022, 7, 1, 16, 7, 15, 707570), max_length=32)),
                ('films', models.ManyToManyField(to='films.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='films.genre'),
        ),
    ]
