# Generated by Django 4.0.5 on 2022-07-01 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='genre',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 16, 13, 16, 146089), max_length=64),
        ),
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 16, 13, 16, 146089), max_length=32),
        ),
    ]
