# Generated by Django 4.0.5 on 2022-07-01 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_poster_alter_genre_createdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 16, 15, 5, 241054), max_length=64),
        ),
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 16, 15, 5, 241054), max_length=32),
        ),
    ]
