# Generated by Django 4.0.5 on 2022-07-01 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_genre_createdt_alter_productor_createdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='createDT',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='createDT',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 16, 28, 0, 998082), max_length=32),
        ),
        migrations.AlterField(
            model_name='productor',
            name='data_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
