# Generated by Django 4.0.5 on 2022-07-01 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_createdt_alter_genre_createdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 16, 29, 14, 390425), max_length=32),
        ),
        migrations.AlterField(
            model_name='productor',
            name='data_birth',
            field=models.DateField(null=True),
        ),
    ]
