# Generated by Django 4.0.5 on 2022-07-01 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_productor_createdt_alter_productor_data_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 1, 17, 21, 15, 437798), max_length=32),
        ),
    ]
