# Generated by Django 4.0.5 on 2022-07-04 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0039_alter_productor_createdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='image_photo',
            field=models.ImageField(null=True, upload_to='productors'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(null=True, upload_to='movies_poster'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 4, 19, 26, 31, 986867), max_length=32),
        ),
    ]
