# Generated by Django 4.0.5 on 2022-07-04 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0040_productor_image_photo_alter_film_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 4, 19, 37, 31, 946518), max_length=32),
        ),
    ]
