# Generated by Django 4.0.5 on 2022-07-04 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0041_alter_productor_createdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 4, 20, 9, 47, 302863), max_length=32),
        ),
        migrations.AlterField(
            model_name='productor',
            name='films',
            field=models.ManyToManyField(null=True, to='films.film'),
        ),
    ]
