# Generated by Django 4.0.5 on 2022-07-04 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0043_alter_productor_createdt_alter_productor_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 4, 20, 19, 5, 86175), max_length=32),
        ),
    ]
