# Generated by Django 4.0.5 on 2022-07-04 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0045_alter_genre_id_alter_productor_createdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 4, 20, 52, 35, 91668), max_length=32),
        ),
    ]
