# Generated by Django 4.0.5 on 2022-07-05 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0060_alter_productor_createdt_alter_productor_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 5, 19, 59, 13, 865759), max_length=32),
        ),
    ]
