# Generated by Django 4.0.5 on 2022-07-05 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0063_alter_productor_createdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 5, 21, 20, 12, 584905), max_length=32),
        ),
        migrations.AlterField(
            model_name='productor',
            name='image_photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
