# Generated by Django 4.0.5 on 2022-07-07 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0073_alter_productor_createdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='createDT',
            field=models.CharField(default=datetime.datetime(2022, 7, 7, 15, 10, 8, 577410), max_length=32),
        ),
    ]
